# Site settings
title: Systems immunology lab at the University of Pittsburgh
lab_name: Jishnu Lab
author: >
  Simar, Swapnil and the Jishnu laboratory
institution: UPitt
email: yadavsi@pitt.edu
description: "Machine Learning, Networks, Immunology, Coffee and Music"
baseurl: ""
url: "https://simaryadav.github.io"
twitter_username: simaryadav
github_username:  simaryadav
images_dir: "/images/"
theme: jekyll-theme-merlot
# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
